openapi: "3.1.0"
info:
  title: API Users
  version: "1.0"
paths:
  /products:

    get:
      summary: Obtienes todos los productos
      tags:
        - "Productos"
      responses:
        "200":
          description: Todos los productos fueron obtenidos (Se devuelve como un handleBars)
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      summary: Crea un producto
      tags:
      - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/createUpdateProduct"
    delete:
      summary: Borra todos los productos
      tags:
        - "Productos"
      responses:
        "200":
          description: Todos los productos fueron borrados
        "400":
          description: Bad request
        "500":
          description: Internal server error          
                  
  /products/{productID}:
    get:
      summary: Obtienes un solo producto
      tags:
        - Productos
      parameters:
        - name: productID
          in: path
          required: true
          description: id del producto que buscas
          schema:
            type: string
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        "400":
          description: Bad request
        "500":
          description: Internal server error

    delete:
      summary: borra un producto
      tags:
        - Productos
      parameters:
        - name: productID
          in: path
          required: true
          description: id del producto que borrarras
          schema:
            type: string
      responses:
        "200":
          description: Producto borrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        "400":
          description: Bad request
        "500":
          description: Internal server error      

    patch:
      summary: Actualiza un producto
      tags:
      - Productos
      parameters:
        - name: productID
          in: path
          required: true
          description: id del producto que buscas
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/createUpdateProduct"
              responses:
              "200":
              description: Producto creado
               
              
components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: string
          description: Id de mongo
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: string
          description: Codigo del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: stock del producto
        category:
          type: number
          description: Categoria del producto
        image:
          type: string
          description: Imagen del producto (Debe ser URL)
        owner:
          type: string
          description: Propiertario del producto
      example:
         _id: ObjectId("87whc8hfte78hcs9dhg8")
         title: Keyboard
         description: Keyboard RGB
         code: fef243
         price: 50
         stock: 1000
         category: 3
         image: https://imagen
         owner: Pablo


  requestBodies:      
    createUpdateProduct:
      description: Body con la info del producto a crear
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: string
          description: Codigo del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: stock del producto
        category:
          type: number
          description: Categoria del producto
        image:
          type: string
          description: Imagen del producto (Debe ser URL)
        owner:
          type: string
          description: Propiertario del producto